### ISSUE TITLE
Suggestion: Refactor `report` API to take an `options` object

### ISSUE THREAD

**Issue by antross** [webhintio/rfcs#47] opened 2018-10-17 15:58 UTC
This API has grown to contain a number of optional parameters which can lead to awkward calls like:
```ts
await context.report(resource, null, 'Resource has no content.', undefined, problemLocation);
```

### Current definition
```ts
public async report(resource: string, element: IAsyncHTMLElement | null, message: string, content?: string, location?: ProblemLocation, severity?: Severity, codeSnippet?: string): Promise<void>
```

The only two pieces that are truly required are the first and third parameters (`resource` and `message`).

### Proposed change
 I propose either replacing or providing an alternate version of this API which takes an `options` object instead (depending on whether we're willing to take this as a breaking change):

```ts
type ReportOptions = {
    codeSnippet?: string;
    content?: string;
    element?: IAsyncHTMLElement | null;
    location?: ProblemLocation;
    severity?: Severity;
};

public async report(resource: string, message: string, options?: ReportOptions): Promise<void>
```

**Comment by molant** [comment] 2018-10-17 16:13
Could be a duplicate of https://github.com/webhintio/hint/issues/258. I'm ok closing that one in favor of this. @antross ?

**Comment by antross** [comment] 2018-10-17 16:17
> I'm ok closing that one in favor of this

Sure, looks like we were thinking along the same lines. :)

Looking there I also see we apparently need to document this API, which we should cover in whatever PR makes this change.

@molant what are your thoughts on replacing the existing API entirely (making this a breaking change)?

**Comment by molant** [comment] 2018-10-17 16:20
I'd like to break as many things as we can as the same time so we don't have a major version every other week. Maybe now is the time with the current pending PRs?
I'd like to get the debugging protocol changes before any breaking change so we can publish it sooner rather than later.

**Comment by antross** [comment] 2018-10-17 16:22
> I'd like to break as many things as we can as the same time so we don't have a major version every other week.

Agreed, and yes now would probably be a good time since I'm sitting on a breaking change PR already. I'll add this to my list for today.

**Comment by molant** [comment] 2018-10-17 16:29
Ups, missed that part 😅
Maybe an updated version in case you find something else while looking at all the places where we use it, although I don't remember any weird usage of this.
Otherwise your proposal LGTM. @webhintio/core what do you think of @antross proposed changes?

**Comment by sarvaje** [comment] 2018-10-17 16:34
I like the idea!

**Closed** 2018-11-05 21:15 UTC
